In [12]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import os
import datetime
pd.options.display.max_rows = 20

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

import warnings
warnings.filterwarnings(action='ignore')

## 아래는 matplotlib 한국어 표시해주는 코드

from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

In [13]:
stores = pd.read_excel('점포수_18부터.xlsx')

In [14]:
stores.head()

,구,행정구역,생활밀접업종,2018년 2분기 전체점포수,2018년 2분기 프랜차이점포수,2018년 2분기 일점포수,2019년 2분기 전점포수,2019년 2분기 프랜차이점포수,2019년 2분기 일점포수,2020년 2분기 전점포수,...,2020년 2분기 일점포수,2018년 1분기 전점포수,2018년 1분기 프랜차이점포수,2018년 1분기 일점포수,2019년 1분기 전점포수,2019년 1분기 프랜차이점포수,2019년 1분기 일점포수,2020년 1분기 전점포수,2020년 1분기 프랜차이점포수,2020년 1분기 일점포수
0,종로구,청운효자동,업종 전체,735,24,711,737,22,715,757,...,735,730,24,706,729,23,706,753,22,731
1,종로구,사직동,업종 전체,2562,169,2393,2563,167,2396,2696,...,2494,2560,167,2393,2551,169,2382,2731,206,2525
2,종로구,삼청동,업종 전체,663,43,620,640,38,602,706,...,656,654,45,609,647,40,607,724,48,676
3,종로구,부암동,업종 전체,386,33,353,375,34,341,397,...,361,383,31,352,370,34,336,393,36,357
4,종로구,평창동,업종 전체,572,34,538,546,32,514,570,...,537,585,35,550,552,32,520,571,35,536

In [15]:
stores.columns

stores = stores[['구', '행정구역', '생활밀접업종', 
         '2018년 1분기 일점포수', '2018년 1분기 프랜차이점포수', '2018년 1분기 전점포수',
         '2018년 2분기 일점포수', '2018년 2분기 프랜차이점포수','2018년 2분기 전체점포수', 
         '2019년 1분기 일점포수', '2019년 1분기 프랜차이점포수', '2019년 1분기 전점포수',
         '2019년 2분기 일점포수','2019년 2분기 프랜차이점포수','2019년 2분기 전점포수',
         '2020년 1분기 일점포수','2020년 1분기 프랜차이점포수','2020년 1분기 전점포수',
         '2020년 2분기 일점포수','2020년 2분기 프랜차이점포수', '2020년 2분기 전점포수'       
       
       ]]

In [16]:
stores_dong = stores[['구', '행정구역', '생활밀접업종', 
         '2018년 1분기 일점포수', '2018년 1분기 프랜차이점포수', '2018년 1분기 전점포수',
         '2018년 2분기 일점포수', '2018년 2분기 프랜차이점포수','2018년 2분기 전체점포수', 
         '2019년 1분기 일점포수', '2019년 1분기 프랜차이점포수', '2019년 1분기 전점포수',
         '2019년 2분기 일점포수','2019년 2분기 프랜차이점포수','2019년 2분기 전점포수',
         '2020년 1분기 일점포수','2020년 1분기 프랜차이점포수','2020년 1분기 전점포수',
         '2020년 2분기 일점포수','2020년 2분기 프랜차이점포수', '2020년 2분기 전점포수'       
       
       ]]

In [17]:
stores_dong

,구,행정구역,생활밀접업종,2018년 1분기 일점포수,2018년 1분기 프랜차이점포수,2018년 1분기 전점포수,2018년 2분기 일점포수,2018년 2분기 프랜차이점포수,2018년 2분기 전체점포수,2019년 1분기 일점포수,...,2019년 1분기 전점포수,2019년 2분기 일점포수,2019년 2분기 프랜차이점포수,2019년 2분기 전점포수,2020년 1분기 일점포수,2020년 1분기 프랜차이점포수,2020년 1분기 전점포수,2020년 2분기 일점포수,2020년 2분기 프랜차이점포수,2020년 2분기 전점포수
0,종로구,청운효자동,업종 전체,706,24,730,711,24,735,706,...,729,715,22,737,731,22,753,735,22,757
1,종로구,사직동,업종 전체,2393,167,2560,2393,169,2562,2382,...,2551,2396,167,2563,2525,206,2731,2494,202,2696
2,종로구,삼청동,업종 전체,609,45,654,620,43,663,607,...,647,602,38,640,676,48,724,656,50,706
3,종로구,부암동,업종 전체,352,31,383,353,33,386,336,...,370,341,34,375,357,36,393,361,36,397
4,종로구,평창동,업종 전체,550,35,585,538,34,572,520,...,552,514,32,546,536,35,571,537,33,570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,강동구,성내2동,업종 전체,1327,106,1433,1325,104,1429,1304,...,1407,1310,103,1413,1277,113,1390,1273,109,1382
420,강동구,성내3동,업종 전체,1799,147,1946,1797,144,1941,1752,...,1896,1769,141,1910,1811,151,1962,1797,150,1947
421,강동구,길동,업종 전체,2618,241,2859,2617,233,2850,2560,...,2792,2541,229,2770,2575,247,2822,2545,248,2793
422,강동구,둔촌1동,업종 전체,166,2,168,156,2,158,141,...,144,139,3,142,127,6,133,126,6,132
423,강동구,둔촌2동,업종 전체,1005,91,1096,1003,91,1094,989,...,1074,987,86,1073,995,85,1080,999,86,1085

In [18]:
stores_dong.drop(['행정구역', '생활밀접업종'], axis=1, inplace=True)

In [19]:
stores_dong.to_csv('처리/점포수_동.csv', encoding='cp949')

In [85]:

# abalone.groupby(abalone['sex']).mean()
# abalone.groupby('sex').mean()

stores_gu = stores_dong.groupby(stores['구']).sum()

In [87]:
#store dong g 컬럼으로 구 까지 적어줬는데 그러면 오류가 납니다. 또 피봇테이블이라서 구는 배줘야하나봐요.. 피복..알고싶다...

stores_gu.columns = [
         '2018년 1분기 일반 점포수', '2018년 1분기 프랜차이즈 점포수', '2018년 1분기 전체 점포수',
         '2018년 2분기 일반 점포수', '2018년 2분기 프랜차이즈 점포수','2018년 2분기 전체 점포수', 
         '2019년 1분기 일반 점포수', '2019년 1분기 프랜차이즈 점포수', '2019년 1분기 전체 점포수',
         '2019년 2분기 일반 점포수','2019년 2분기 프랜차이즈 점포수','2019년 2분기 전체 점포수',
         '2020년 1분기 일반 점포수','2020년 1분기 프랜차이즈 점포수','2020년 1분기 전체 점포수',
         '2020년 2분기 일반 점포수','2020년 2분기 프랜차이즈 점포수', '2020년 2분기 전체 점포수'       
       
       ]

In [88]:
stores_gu

,2018년 1분기 일반 점포수,2018년 1분기 프랜차이즈 점포수,2018년 1분기 전체 점포수,2018년 2분기 일반 점포수,2018년 2분기 프랜차이즈 점포수,2018년 2분기 전체 점포수,2019년 1분기 일반 점포수,2019년 1분기 프랜차이즈 점포수,2019년 1분기 전체 점포수,2019년 2분기 일반 점포수,2019년 2분기 프랜차이즈 점포수,2019년 2분기 전체 점포수,2020년 1분기 일반 점포수,2020년 1분기 프랜차이즈 점포수,2020년 1분기 전체 점포수,2020년 2분기 일반 점포수,2020년 2분기 프랜차이즈 점포수,2020년 2분기 전체 점포수
구,,,,,,,,,,,,,,,,,,
강남구,50745,3848,54593,50621,3845,54466,50058,3738,53796,50134,3737,53871,51504,4371,55875,51322,4353,55675
강동구,19438,1750,21188,19404,1738,21142,19030,1697,20727,18976,1689,20665,19073,1901,20974,19038,1897,20935
강북구,12550,993,13543,12486,1001,13487,12254,992,13246,12256,984,13240,12342,1075,13417,12395,1066,13461
강서구,22729,2259,24988,22713,2279,24992,22669,2240,24909,22734,2253,24987,23269,2633,25902,23377,2632,26009
관악구,18351,1759,20110,18256,1747,20003,17934,1702,19636,17917,1691,19608,17826,1908,19734,17807,1903,19710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
용산구,17876,1046,18922,17860,1051,18911,17555,1047,18602,17567,1026,18593,17869,1178,19047,17741,1183,18924
은평구,17003,1420,18423,16913,1416,18329,16652,1414,18066,16668,1410,18078,16759,1554,18313,16778,1572,18350
종로구,23718,1409,25127,23693,1415,25108,23412,1382,24794,23475,1375,24850,23065,1616,25500,23710,1608,25318
중구,39886,1762,41648,39453,1765,41218,37790,1721,39511,37472,1709,39181,38243,2095,40338,37953,2062,40015
중랑구,15099,1185,16284,15054,1176,16230,14833,1160,15993,14872,1161,16033,14886,1275,16161,14894,1286,16180

# 전체뽑기

In [89]:
#와!!!!!!!!!!!!!! regex로 뽑기

#버리는 우리의 코드
# stores_dong_tot = stores_dong_g[[
#           '2018년 1분기 전체 점포수',
#          '2018년 2분기 전체 점포수', 
#           '2019년 1분기 전체 점포수',
#          '2019년 2분기 전체 점포수',
#          '2020년 1분기 전체 점포수',
#           '2020년 2분기 전체 점포수'       
#        ]]


stores_gu_tot = stores_gu.filter(regex='\전체')

In [90]:
stores_gu_tot

,2018년 1분기 전체 점포수,2018년 2분기 전체 점포수,2019년 1분기 전체 점포수,2019년 2분기 전체 점포수,2020년 1분기 전체 점포수,2020년 2분기 전체 점포수
구,,,,,,
강남구,54593,54466,53796,53871,55875,55675
강동구,21188,21142,20727,20665,20974,20935
강북구,13543,13487,13246,13240,13417,13461
강서구,24988,24992,24909,24987,25902,26009
관악구,20110,20003,19636,19608,19734,19710
...,...,...,...,...,...,...
용산구,18922,18911,18602,18593,19047,18924
은평구,18423,18329,18066,18078,18313,18350
종로구,25127,25108,24794,24850,25500,25318
중구,41648,41218,39511,39181,40338,40015
중랑구,16284,16230,15993,16033,16161,16180

In [91]:
# 연습: stores_dong_tot['2018년 1분기 랭크'] = stores_dong_tot['2018년 1분기 전체 점포수'].rank(ascending =False)


for j in range(1,2):
    for i in range(18,21):
        stores_gu_tot[f'20{i}년 {j}분기 랭크'] = stores_gu_tot[f'20{i}년 {j}분기 전체 점포수'].rank(ascending =False)

In [92]:
stores_gu_tot

,2018년 1분기 전체 점포수,2018년 2분기 전체 점포수,2019년 1분기 전체 점포수,2019년 2분기 전체 점포수,2020년 1분기 전체 점포수,2020년 2분기 전체 점포수,2018년 1분기 랭크,2019년 1분기 랭크,2020년 1분기 랭크
구,,,,,,,,,
강남구,54593,54466,53796,53871,55875,55675,1.0,1.0,1.0
강동구,21188,21142,20727,20665,20974,20935,11.0,11.0,11.0
강북구,13543,13487,13246,13240,13417,13461,24.0,24.0,24.0
강서구,24988,24992,24909,24987,25902,26009,8.0,7.0,7.0
관악구,20110,20003,19636,19608,19734,19710,12.0,12.0,12.0
...,...,...,...,...,...,...,...,...,...
용산구,18922,18911,18602,18593,19047,18924,14.0,14.0,13.0
은평구,18423,18329,18066,18078,18313,18350,16.0,16.0,16.0
종로구,25127,25108,24794,24850,25500,25318,7.0,8.0,8.0
중구,41648,41218,39511,39181,40338,40015,2.0,2.0,2.0
중랑구,16284,16230,15993,16033,16161,16180,20.0,20.0,20.0

# 프차뽑기

In [93]:
stores_gu_fran = stores_gu.filter(regex='\프랜차이즈')

# 일반뽑기

In [94]:
stores_gu_gen = stores_gu.filter(regex='\일반')

# 임대료

In [141]:
rent = pd.read_excel('임대시세_구 (1).xlsx')

In [142]:
rent = rent.groupby('행정구역').sum()
rent.head()

,2018년 1분기 환산 임대료\t전체,2018년 1분기 환산 임대료\t1층,2018년 1분기 환산 임대료\t1층 외,2019년 1분기 환산 임대료\t전체,2019년 1분기 환산 임대료\t1층,2019년 1분기 환산 임대료 1층 외,2020년 1분기 환산 임대료\t전체,2020년 1분기 환산 임대료\t1층,2020년 1분기 환산 임대료\t1층 외,2018년 2분기 환산 임대료\t전체,2018년 2분기 환산 임대료\t1층,2018년 2분기 환산 임대료\t1층 외,2019년 2분기 환산 임대료\t전체,2019년 2분기 환산 임대료\t1층,2019년 2분기 환산 임대료\t1층 외,2020년 2분기 환산 임대료\t전체,2020년 2분기 환산 임대료\t1층,2020년 2분기 환산 임대료\t1층 외
행정구역,,,,,,,,,,,,,,,,,,
강남구,127807,161553,103703,128090,158842,107966,140179,172542,119247,127658,159885,105883,132143,164009,111717,136221,171681,115950
강동구,87539,106293,57549,90306,109830,62378,94621,115081,62930,88441,107111,59334,89901,109765,60847,104536,125177,75944
강북구,84489,94208,64069,86793,97756,66874,86500,94772,70279,80861,91179,58644,88452,97288,72741,86837,99833,64177
강서구,100028,121232,70581,108286,133229,76132,102080,129030,75464,102124,124556,73641,106206,133785,70141,100997,129933,73660
관악구,98805,121236,63477,104635,128760,69761,104626,124404,71939,98901,123668,59836,107251,129783,74349,104060,124519,73453

In [143]:
# 전체 = {1층 임대료 + 1층 외 임대료*(층 수-1)} / 층 수

rent_ave = rent.filter(regex = '\전체')
rent_else = rent.filter(regex = '\층 외')
rent_first = rent.filter(regex = '\층$')

# 건물 전체 평균 임대료로

In [144]:
rent_ave.head()

,2018년 1분기 환산 임대료\t전체,2019년 1분기 환산 임대료\t전체,2020년 1분기 환산 임대료\t전체,2018년 2분기 환산 임대료\t전체,2019년 2분기 환산 임대료\t전체,2020년 2분기 환산 임대료\t전체
행정구역,,,,,,
강남구,127807,128090,140179,127658,132143,136221
강동구,87539,90306,94621,88441,89901,104536
강북구,84489,86793,86500,80861,88452,86837
강서구,100028,108286,102080,102124,106206,100997
관악구,98805,104635,104626,98901,107251,104060

In [146]:
rent_ave['2018년 1분기 전체 임대료 비율'] = round((rent_ave['2018년 1분기 환산 임대료\t전체'] / rent_ave.mean()[0]) * 100)
rent_ave['2019년 1분기 전체 임대료 비율'] = round((rent_ave['2019년 1분기 환산 임대료\t전체'] / rent_ave.mean()[1]) * 100)
rent_ave['2020년 1분기 전체 임대료 비율'] = round((rent_ave['2020년 1분기 환산 임대료\t전체'] / rent_ave.mean()[2]) * 100)
rent_ave['2018년 2분기 전체 임대료 비율'] = round((rent_ave['2018년 2분기 환산 임대료\t전체'] / rent_ave.mean()[3]) * 100)
rent_ave['2019년 2분기 전체 임대료 비율'] = round((rent_ave['2019년 2분기 환산 임대료\t전체'] / rent_ave.mean()[4]) * 100)
rent_ave['2020년 2분기 전체 임대료 비율'] = round((rent_ave['2020년 2분기 환산 임대료\t전체'] / rent_ave.mean()[5]) * 100)

In [147]:
rent_ave

,2018년 1분기 환산 임대료\t전체,2019년 1분기 환산 임대료\t전체,2020년 1분기 환산 임대료\t전체,2018년 2분기 환산 임대료\t전체,2019년 2분기 환산 임대료\t전체,2020년 2분기 환산 임대료\t전체,2018년 1분기 전체 임대료 비율,2019년 1분기 전체 임대료 비율,2020년 1분기 전체 임대료 비율,2018년 2분기 전체 임대료 비율,2019년 2분기 전체 임대료 비율,2020년 2분기 전체 임대료 비율
행정구역,,,,,,,,,,,,
강남구,127807,128090,140179,127658,132143,136221,120.0,117.0,127.0,119.0,120.0,121.0
강동구,87539,90306,94621,88441,89901,104536,82.0,82.0,86.0,83.0,81.0,93.0
강북구,84489,86793,86500,80861,88452,86837,79.0,79.0,78.0,76.0,80.0,77.0
강서구,100028,108286,102080,102124,106206,100997,94.0,99.0,92.0,96.0,96.0,90.0
관악구,98805,104635,104626,98901,107251,104060,92.0,95.0,95.0,93.0,97.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...
용산구,111753,113739,113361,110597,116938,116530,105.0,104.0,102.0,103.0,106.0,104.0
은평구,86558,91850,94239,87871,92886,96220,81.0,84.0,85.0,82.0,84.0,86.0
종로구,184919,183435,175410,180495,191292,170556,173.0,167.0,159.0,169.0,173.0,152.0
중구,218632,214273,242109,216588,214810,245324,205.0,196.0,219.0,203.0,195.0,218.0
중랑구,71153,76167,77354,70544,78050,78716,67.0,70.0,70.0,66.0,71.0,70.0

1. 핫플비핫플은 시각화만 하면 됨
-- 핫플 비핫플 다른 기준(상권변화지표,예상매출...)
2. 귀미한(개폐업)_ 날짜 decimal 처리 (x) 
3. 귀미한_org_food Nan값처리 (x)
3. 귀미한: 폐열률이 어느정도 되는지, 면적과의 상관관계,
4. 점포수 - 어떤 식으로 랭킹을 시각화할 것인지, 동/구 기준? -> 랭킹이 크게 다를 것 같진 않으니 top구를 정해서 거기서 동으로 쪼개도 될것같다(귀)
5. 점포수 - 동/구 어디에 기준으로 쓸것인지 정해야함(가설1에서는 구로, 가설2에서는 동을 독립변수로?)
6. 임대료

1. 핫플비핫플
-- 상권변화지표
-- 상권 추정 매출
-- 유동인구


2. 폐업
* 결측치처리
* decimal 정리
****
* 구 별 폐업률
* 소재지 면적 비교
* 구별 폐업 심화 수준
* 업태 망하는거

3. 점포수
****
* 3년동안 변화 추이
* 3년 동안의 전체 점포수와 임대료의 관계성 파악
* 3년 동안의 일반 점포수와 임대료의 관계성
* 3년 동안의 프랜차이즈 점포수와 임대료의 관계성 
* 3개년 rank 10인애들 뽑아서, 순위 변경 확인
* top5r개 구를 정해서 
* (시간이되면) 동을 다시 살펴보자!

4. 임대료
****
* 3년 변화 추이
* 3개년 상위하위 rank 10인애들 뽑아서, 순위 변경 확인
* top5r개 구를 정해서 

* (시간이 되면) 프랜차이즈, 일반 점포와 임대료 변화 비교

In [150]:
rent_ave.head()

,2018년 1분기 환산 임대료\t전체,2019년 1분기 환산 임대료\t전체,2020년 1분기 환산 임대료\t전체,2018년 2분기 환산 임대료\t전체,2019년 2분기 환산 임대료\t전체,2020년 2분기 환산 임대료\t전체,2018년 1분기 전체 임대료 비율,2019년 1분기 전체 임대료 비율,2020년 1분기 전체 임대료 비율,2018년 2분기 전체 임대료 비율,2019년 2분기 전체 임대료 비율,2020년 2분기 전체 임대료 비율
행정구역,,,,,,,,,,,,
강남구,127807,128090,140179,127658,132143,136221,120.0,117.0,127.0,119.0,120.0,121.0
강동구,87539,90306,94621,88441,89901,104536,82.0,82.0,86.0,83.0,81.0,93.0
강북구,84489,86793,86500,80861,88452,86837,79.0,79.0,78.0,76.0,80.0,77.0
강서구,100028,108286,102080,102124,106206,100997,94.0,99.0,92.0,96.0,96.0,90.0
관악구,98805,104635,104626,98901,107251,104060,92.0,95.0,95.0,93.0,97.0,93.0

# 1. 3년 동안의 전체 점포수 변화 추이 
-> 코로나19 영향력이 점포수 변화에 영향을 주었는지
# 2. 3년 동안의 전체 점포수와 임대료의 관계성 파악
# 3. 3년 동안의 일반 점포수와 임대료의 관계성
# 4. 3년 동안의 프랜차이즈 점포수와 임대료의 관계성 
-> 일반 점포와 프랜차이즈 점포 중에 더 타격을 입은 점포

In [ ]:
d